

[bell]
animation = "EaseOutExpo"


[general]
import = [
    "../../.cache/wal/colors-alacritty.toml"
]




[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 9.5

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window]
opacity = 0.95

[window.padding]
x = 5
y = 5



